### ISSUE TITLE
nsml submit 시 ResourceExhaustedError

### ISSUE THREAD

**Issue by ttagu99** [AiHackathon2018/AI-Vision#105]
submit 시 아래처럼 에러가 납니다. 
 -t 옵션 붙이면 정상 수행 되구요.
어차피 train 이 한번된것이고, -t로 정상 수행 되는거 봐서는 gpu memory 부족은 아닌거 같은데..
어떤 문제 일까요?

C:\Users\ttagu\github\naver_hack>nsml submit Zonber/ir_ph1_v2/79 42
........
Building docker image. It might take for a while
..........Traceback (most recent call last):
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,128,109,109] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node block2_sepconv2/separable_conv2d}} = Conv2D[T=DT_FLOAT, _class=["loc:@block2_sepconv2_bn/cond/FusedBatchNorm/Switch"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block2_sepconv2/separable_conv2d/depthwise, block2_sepconv2/pointwise_kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node dropout_1/cond/Merge/_2691}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1680_dropout_1/cond/Merge", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

..Error: Fail to get prediction result: Zonber/ir_ph1_v2/79/42
time="2019/01/06 10:24:33.008" level=fatal msg="Internal server error"

**Comment by Hackoperation** [comment]
안녕하세요. 
`submit -t`는 데이터의 포맷 및 인퍼런스가 이상없이 잘 동작하는지 확인하는 용도로 데이터를 10개만 전달해주는데요,

실제 `submit`을 하게된다면 전체 test_dataset이 들어와서 메모리 관련된 에러가 발생할수 있습니다.

위와 관련된 전체 에러로그는 다음과 같습니다
```python
  File "main.py", line 82, in infer
    reference_vecs = get_feature_layer([reference_img, 0])[0]
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,128,109,109] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block2_sepconv2/separable_conv2d}} = Conv2D[T=DT_FLOAT, _class=["loc:@block2_sepconv2_bn/cond/FusedBatchNorm/Switch"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block2_sepconv2/separable_conv2d/depthwise, block2_sepconv2/pointwise_kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
