### ISSUE TITLE
submit 질문

### ISSUE THREAD

**Issue by vkeh9656** [AiHackathon2018/AI-Vision#120]
기존에 진행했던 모델이 제출이 안되서 혹여나 프로토콜을 망가뜨리진 않았나싶어
github에서 제공하는 main.py 모델을 session run을 완료 후 제출해보고 있습니다.
하지만,

........
Building docker image. It might take for a while
........

이후 1시간이 지난 후에 

Error: Session does not respond
time=" #실행시간  "  level=fatal msg='internal server error'
의 로그가 추가로 발생합니다. 

원래 github에서 제공하신 main.py도 바로 제출이 안되는 모델인가요?

**Comment by nsml-admin** [comment]
Session이 1시간이내에 서브밋을 못한경우입니다.

세션네임들을 알려주시면 확인해보겠습니다.

**Comment by vkeh9656** [comment]
Session name : TEAM_PKJ/ir_ph1_v2/103 1 로 제출해보았습니다.
submit 구동되는지 테스트 차원에 github에서 제공한 main.py 에서 그대로 했는데도 안되네요.

**Comment by vkeh9656** [comment]
에러 로그는 다음과 같이 떴습니다.

dataset path /data/ir_ph1_v2
7104 train samples
Traceback (most recent call last): 
File "main.py", line 221, in <module> 
shuffle=True) 
File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 952, in fit 
batch_size=batch_size) 
File "/opt/conda/lib/python3.5/site-packages/keras/engine/training.py", line 751, in _standardize_user_data exception_prefix='input') 
File "/opt/conda/lib/python3.5/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have shape (224, 224, 3) but got array with shape (256, 256, 3)
User session exited

이래서 shape을 맞추다보니 사이즈 바꿨습니다.
그래서 저 shape을 256으로 바꾸면 session run이 되서 모델생성은 되었습니다.(submit은 x)

**Comment by vkeh9656** [comment]
해결되었습니다. 감사합니다.
제공해주신 가이드라인에 이런 사항을 확인을 못했었는데
이런 문제가 생긴 원인을 알고 싶습니다. 확인 가능할까요?

**Comment by nsml-admin** [comment]
소스코드를 받고 최초에 run하실때에 프리프로세싱 파일이 잘못저장된것같습니다. (`input_shape = (256, 256, 3)`으로 되어있엇습니다.)

그이후에 파일이 캐싱되어서 계속 그파일을 불러왔던것같습니다.

감사합니다.
