### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by insurgent92** [AiHackathon2018/AI-Vision#134]
Session : `team_38/ir_pr1_v2/124`

안녕하세요! 
preprocess을 새롭게 적용한 cache 파일을 만들기 위해서
data_loader를 새롭게 정의하고 pickle 파일을 덤핑하려는 도중 다음과 같은 에러가 발생합니다. 

Traceback (most recent call last):    
File "main.py", line 203, in <module>    
output_path=output_path)    
File "/app/nsml/client.py", line 574, in cache     
_ = preprocess_fn(**kwargs)    
File "/app/data_loader.py", line 69, in train_data_loader_224   
pickle.dump(img_list, img_f)   
OSError: [Errno 28] No space left on deviceUser session exited

**Comment by nsml-admin** [comment]
안녕하세요~

세션 내에서 한계치까지 데이터를 저장할 때 위와 같은 에러 메시지가 발생합니다

현재의 세션 내에서 저장할 수 있는 용량의 한계는 10G입니다.

감사합니다.

**Comment by insurgent92** [comment]
@nsml-admin 아하 감사합니다!
그렇다면 세션에 공간을 비울 수 있는 방법이 따로 있나요?

**Comment by nsml-admin** [comment]
`nsml sh` 명령어를 활용하면 정리할 수 있을것 같습니다 :)

**Comment by smartdolphin** [comment]
nsml sh 명령어를 아무리 뒤져봐도 안나오는데 예시가 있을까요?
