### ISSUE TITLE
nsml load 관련 에러

### ISSUE THREAD

**Issue by SeonhwaLee** [AiHackathon2018/AI-Vision#142]
### 기타

안녕하세요, 
기존에 모델구조를 변경하지 않고, 모델을 불러와서 재학습시키려 하는데, 여러번 실행할때마다 에러나는 위치가 다릅니다. 에러원인이 어떤건지 알 수 있을까요?

#session 178 실행시 에러
2019-01-10 13:22:53.499676: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA2019-01-10 13:22:53.703309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero2019-01-10 13:22:53.704036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531pciBusID: 0000:00:06.0totalMemory: 23.88GiB freeMemory: 23.71GiB2019-01-10 13:22:53.704072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 02019-01-10 13:22:54.292588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:2019-01-10 13:22:54.292656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] 0 2019-01-10 13:22:54.292666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0: N 2019-01-10 13:22:54.293184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 23006 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:00:06.0, compute capability: 6.1)Traceback (most recent call last): File "main_vgg_finetuned.py", line 231, in <module> nsml.load(51, session='INLine/ir_ph1_v2/167') File "/app/nsml/client.py", line 439, in load load_fn(temp_file.name) File "main_vgg_finetuned.py", line 41, in load model.load_weights(file_path) File "/opt/conda/lib/python3.5/site-packages/keras/engine/network.py", line 1166, in load_weights f, self.layers, reshape=reshape) File "/opt/conda/lib/python3.5/site-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group K.batch_set_value(weight_value_tuples) File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2470, in batch_set_value get_session().run(assign_ops, feed_dict=feed_dict) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run run_metadata_ptr) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1086, in _run str(subfeed_t.get_shape())))ValueError: Cannot feed value of shape (512, 256, 3, 3) for Tensor 'Placeholder_12:0', which has shape '(3, 3, 256, 256)'Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2b80361abc50>>Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 696, in __del__TypeError: 'NoneType' object is not callableUser session exited

#session 180 실행시 에러
2019-01-10 13:25:29.814533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA2019-01-10 13:25:30.030512: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero2019-01-10 13:25:30.031344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: name: Tesla P40 major: 6 minor: 1 memoryClockRate(GHz): 1.531pciBusID: 0000:00:06.0totalMemory: 23.88GiB freeMemory: 23.71GiB2019-01-10 13:25:30.031396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 02019-01-10 13:25:30.705372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:2019-01-10 13:25:30.705433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] 0 2019-01-10 13:25:30.705445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0: N 2019-01-10 13:25:30.705971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 23006 MB memory) -> physical GPU (device: 0, name: Tesla P40, pci bus id: 0000:00:06.0, compute capability: 6.1)Traceback (most recent call last): File "main_vgg_finetuned.py", line 226, in <module> nsml.load(51, session='INLine/ir_ph1_v2/167') File "/app/nsml/client.py", line 439, in load load_fn(temp_file.name) File "main_vgg_finetuned.py", line 41, in load model.load_weights(file_path) File "/opt/conda/lib/python3.5/site-packages/keras/engine/network.py", line 1166, in load_weights f, self.layers, reshape=reshape) File "/opt/conda/lib/python3.5/site-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group K.batch_set_value(weight_value_tuples) File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2470, in batch_set_value get_session().run(assign_ops, feed_dict=feed_dict) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run run_metadata_ptr) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1086, in _run str(subfeed_t.get_shape())))ValueError: Cannot feed value of shape (512,) for Tensor 'Placeholder_5:0', which has shape '(128,)'User session exited

감사합니다.

**Comment by Hackoperation** [comment]
안녕하세요. 

에러나는 위치는 매번같지만 weight를 load할때의 내용이 달라지는것같습니다. 

load하려는 모델의 구조와 코드안에서의 모델의 구조를 다시 한번확인부탁드립니다.

또한 web에서 각코드의 변경사항을 확인해볼수 있습니다. [참고](https://n-clair.github.io/vision-docs/_build/html/ko_KR/contents/web_interface/check_session_diff.html)
