### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by comisputer** [AiHackathon2018/AI-Vision#171]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **전체 실행 명령어**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**NSML login ID 가 무엇인가요?**
comiputer

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
@nsml-admin
CAU_LOVER/ir_ph1_v2/268 session running과정에서 정상적인 학습도중
아래와 같은 에러가 발생했습니다.
Connection문제같은데 이 에러가 발생하는 이유를 알고싶습니다.

Traceback (most recent call last): File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen chunked=chunked) File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request six.raise_from(e, None) File "<string>", line 2, in raise_from File "/opt/conda/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request httplib_response = conn.getresponse() File "/opt/conda/lib/python3.5/http/client.py", line 1198, in getresponse response.begin() File "/opt/conda/lib/python3.5/http/client.py", line 297, in begin version, status, reason = self._read_status() File "/opt/conda/lib/python3.5/http/client.py", line 258, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/opt/conda/lib/python3.5/socket.py", line 576, in readinto return self._sock.recv_into(b)ConnectionResetError: [Errno 104] Connection reset by peerDuring handling of the above exception, another exception occurred:

**재현방법은 어떻게 되나요?**

**예상했던 동작방식은 무엇인가요?**

**제안하고 싶은 해결방법이 있나요?**

**Comment by smartdolphin** [comment]
저도 같은 문제 발생합니다. 

naverhood/ir_ph1_v2/89

**Comment by SeonhwaLee** [comment]
저도 자주 발생되는데 ㅠㅠ 이유를 알고 싶어요 학습이 잘되다가 세션이 그냥 꺼져버리네요 ㅠㅠ
