### ISSUE TITLE
skcuda.cublas.cublasInternalError

### ISSUE THREAD

**Issue by ttagu99** [AiHackathon2018/AI-Vision#176]
**Informations**
**NSML login ID 가 무엇인가요?**
ttagu99

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
Session Zonber/ir_ph1_v2/303

**재현방법은 어떻게 되나요?**
Session Zonber/ir_ph1_v2/303 is started
....Traceback (most recent call last):
skcuda.cublas.cublasInternalError

scikit-cuda 를 사용할때 발생합니다.
setup.py를 사용해 설치후 사용하는데, 설치가 잘못된것일까요?

**Comment by nsml-admin** [comment]
위 에러와 관련된 로그는 다음과 같습니다.

```python
  File "ensemble_cv.py", line 145, in infer
    sim_matrix_gpu = culinalg.dot(query_vecs_gpu, reference_vecs_gpu_t)
  File "/opt/conda/lib/python3.5/site-packages/skcuda/linalg.py", line 1058, in dot
    add_dot(x_gpu, y_gpu, out, transa, transb, 1.0, 0.0, handle)
  File "/opt/conda/lib/python3.5/site-packages/skcuda/linalg.py", line 937, in add_dot
    ldb, a_gpu.gpudata, lda, beta, c_gpu.gpudata, ldc)
  File "/opt/conda/lib/python3.5/site-packages/skcuda/cublas.py", line 4295, in cublasSgemm
    cublasCheckStatus(status)
  File "/opt/conda/lib/python3.5/site-packages/skcuda/cublas.py", line 178, in cublasCheckStatus
    raise e
skcuda.cublas.cublasInternalError
```
