### ISSUE TITLE
소스가 저장되는 디바이스에 tfrecord를 저장할 때 공간 부족 에러가 발생합니다.

### ISSUE THREAD

**Issue by jireh-father** [AiHackathon2018/AI-Vision#203]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Windows
- **client version(please show nsml --version)**: Built: 2019-01-22T22:32:44+09:00
- **전체 실행 명령어**: nsml run -d ir_ph2 -e trainer_2st.py

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**: https://hack.nsml.navercorp.com/terminal/jireh_family/ir_ph2/1

**NSML login ID 가 무엇인가요?**
jireh-father

**문제가 발생한 세션은 어떤건가요? (bug message or screenshot)**
세션: jireh_family/ir_ph3/1

학습전 데이터셋을 tfrecord형식으로 소스 경로에 저장한 후 학습을 하는 방식으로 진행하고 있습니다.
그런데 아래처럼 tfrecord를 저장할 경우 데이터 부족 에러가 발생합니다.

Traceback (most recent call last): File "trainer_2st.py", line 253, in <module> tb.make_tfrecords("ir_ph1_v2", "train", train_dataset_path, "./dataset/train/", 4, 3, False) File "/app/tfrecorder_builder.py", line 228, in make_tfrecords num_channels, attr_map) File "/app/tfrecorder_builder.py", line 157, in _convert_dataset tfrecord_writer.write(example.SerializeToString()) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/lib/io/tf_record.py", line 129, in write self._writer.WriteRecord(record, status) File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__ c_api.TF_GetCode(self.status.status))tensorflow.python.framework.errors_impl.ResourceExhaustedError: dataset/train/ir_ph1_v2_train_00002-of-00004.tfrecord; No space left on deviceUser session exited

**재현방법은 어떻게 되나요?**
nsml run -d ir_ph2 -e trainer_2st.py
제 소스를 실행하면 재현됩니다.
원인은 학습 데이터셋을 tfrecord로 만들어서 저장할 때 디바이스의 공간 부족 때문입니다.

**예상했던 동작방식은 무엇인가요?**
tfrecord가 정상적으로 저장된 후 학습 진행

**제안하고 싶은 해결방법이 있나요?**
소스가 저장되는 디바이스에 tfrecord를 저장할 수 있을 만큼의 공간 확보 부탁드립니다.
정 안되면 제 소스를 수정해야겠..지...요....

**Comment by jireh-father** [comment]
tfrecord안만들도록 수정했습니다.
