### ISSUE TITLE
device 용량이 부족하다는 로그가 발생합니다. 

### ISSUE THREAD

**Issue by suwoncjh** [AiHackathon2018/AI-Vision#208]
Traceback (most recent call last): File "main.py", line 184, in <module> output_path=output_path) File "/app/nsml/client.py", line 622, in cache _ = preprocess_fn(**kwargs) File "/app/data_loader.py", line 44, in train_data_loader pickle.dump(img_list, img_f)OSError: [Errno 28] No space left on deviceUser session exited

training data를 pickle로 저장하고 있는데 위와 같은 에러가 발생하며 종료됩니다. 원인을 알 수 있을까요??

**Comment by nsml-admin** [comment]
예선 1차에서 사용하던 코드를 그대로 실행하면 데이터사이즈가 커져서 pickle중에 위와같이 에러가발생할수있습니다.

dataloader에서  generator등으로 모델에 데이터셋을 feeding하는 방법을 고려해보시는게 좋을것같습니다.

https://github.com/AiHackathon2018/AI-Vision/issues/197

**Comment by suwoncjh** [comment]
pickle 저장없이 메모리에 다 올리고 작업해도 메모리 에러가나는데 그냥 조금씩불러다가 트레이닝하는게 방법일까요?
