### ISSUE TITLE
Submit Error

### ISSUE THREAD

**Issue by ChanHyeok** [AiHackathon2018/AI-Vision#61]
학습은 잘 진행되나, 제출 시 다음과 같은 에러가 발생합니다.

D:\Program Files\nsml_client.windows.amd64.hack>nsml submit CodingAndLifeBalance/ir_ph1/21 49
........
Building docker image. It might take for a while
..........Traceback (most recent call last):
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node block1_conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block1_conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, block1_conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

..Error: Fail to get prediction result: CodingAndLifeBalance/ir_ph1/21/49
FATA[2019/01/03 14:12:04.609] Internal server error

**Comment by ChanHyeok** [comment]
-t 로 submit할 시에는 정상적으로 올라갑니다

**Comment by Hackoperation** [comment]
안녕하세요, 

전체 에러 스택은 아래와 같습니다.

우선 테스트 환경과 트레이닝 환경의 다른 점은 없고, 다만 테스트 시에는 `infer` 함수의 queries가 2500씩 들어오고, db는 전체 레퍼런스가 한 번에 들어옵니다.

또한 -t로 할 때는 데이터의 포맷이 잘 맞는지 확인하는 용도이고 데이터 셋은 10개 (queries, db 각각) 씩 들어와서 메모리 문제는 발생하지 않는 것 같습니다.

그 부분을 고려하여서 infer 부분의 코드를 최적화 시키는 게 관건인 것 같습니다.

보안상 전체 로그를 보여줄 수 없는 점 양해 부탁드립니다.

감사합니다.

```python
  File "main.py", line 70, in infer
    reference_vecs = get_feature_layer([reference_img, 0])[0]
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/opt/conda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1127,64,224,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv1/convolution}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](block1_conv1/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, block1_conv1/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```
